#spring.data.mongodb.uri=mongodb://localhost:27017/hotel_management
#spring.data.mongodb.auto-index-creation=true
#
#server.port=8080

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=hotel_management
spring.data.mongodb.auto-index-creation=true

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=salamialameen20@gmail.com
spring.mail.password=Alimzy-01
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true